/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/booking/': RouteRecordInfo<'/admin/booking/', '/admin/booking', Record<never, never>, Record<never, never>>,
    '/admin/booking/[id]/': RouteRecordInfo<'/admin/booking/[id]/', '/admin/booking/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/doctor/': RouteRecordInfo<'/admin/doctor/', '/admin/doctor', Record<never, never>, Record<never, never>>,
    '/admin/doctor/[id]/update': RouteRecordInfo<'/admin/doctor/[id]/update', '/admin/doctor/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/doctor/create': RouteRecordInfo<'/admin/doctor/create', '/admin/doctor/create', Record<never, never>, Record<never, never>>,
    '/admin/history/': RouteRecordInfo<'/admin/history/', '/admin/history', Record<never, never>, Record<never, never>>,
    '/admin/history/[id]/': RouteRecordInfo<'/admin/history/[id]/', '/admin/history/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/patient/': RouteRecordInfo<'/admin/patient/', '/admin/patient', Record<never, never>, Record<never, never>>,
    '/admin/patient/[id]/update': RouteRecordInfo<'/admin/patient/[id]/update', '/admin/patient/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
  }
}
